spring.application.name=backend

# SQLite Datenbank
spring.datasource.url=jdbc:sqlite:vereinsplaner.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# SQL-Ausgaben während der Entwicklung
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Lokaler Backend-Port
server.port=8080